[33mcdf355c[m[33m ([m[1;36mHEAD -> [m[1;32mlatest_branch[m[33m)[m se modifico la seccion de los mejores productos y se elimino un spam
[33mc613e80[m se hiso una seccion de los mejores productos y se coloco un carrusel
[33m81a1121[m seccion de tienda terminada
[33me159bee[m Se agrego un archivo .html de Tienda
[33mb2c229d[m se modifico el fondo del grid layaout a rosa
[33mea57e4b[m Se termino de hacer los grids de las fotografias
[33ma5fa1b2[m se agrego un article de fotografias del jardin y se esta agregando grids de fotos recordatorias del la pagina
[33m252e23c[m se agrego un fixed al background en fotografias
[33mff99ed9[m se creo un inicio de Fotografias
[33mcbdc060[m Se creo una carpeta de pages con el archivo fotografia.html
[33mb55eb71[m se empezo hacer el footer
[33mad6348a[m se modifico el parrafo en container3 de eventos para toda la familia
[33m2d3edae[m Se creo un articulo de eventos para toda la familia
[33m0c0b1a9[m esto es una pruba de explicacion del codigo
[33mb4b26b8[m se corrigieron algunos errores de espacios
[33m0631dd7[m prueba de errores con seba y fede
[33mc9abadb[m Se creo una seccion de Los Gatos invaden el rosedal
[33md52c714[m se creo un article de nuestra casa botanica
[33m9b89b7c[m sec creo un titulo de bienvenida
[33m467c15a[m Se creo un header con nevegacion,titulo y el logo
[33mfb97d27[m initial commit
